import { Topic } from './types';

export const ENERGY_CENTERS: Topic[] = [
    { name: "1st_Chakra", cleanedName: "1st Chakra (Root)" },
    { name: "2nd_Chakra", cleanedName: "2nd Chakra (Sacral)" },
    { name: "3rd_Chakra", cleanedName: "3rd Chakra (Solar Plexus)" },
    { name: "4th_Chakra", cleanedName: "4th Chakra (Heart)" },
    { name: "5th_Chakra", cleanedName: "5th Chakra (Throat)" },
    { name: "6th_Chakra", cleanedName: "6th Chakra (Third Eye)" },
    { name: "7th_Chakra", cleanedName: "7th Chakra (Crown)" },
    { name: "8th_Chakra", cleanedName: "8th Chakra (Soul Star)" },
    { name: "9th_Chakra", cleanedName: "9th Chakra (Spirit Chakra)" },
    { name: "10th_Chakra", cleanedName: "10th Chakra (Universal Chakra)" },
    { name: "11th_Chakra", cleanedName: "11th Chakra (Galactic Chakra)" },
    { name: "12th_Chakra", cleanedName: "12th Chakra (Stellar Gateway)" },
    { name: "13th_Chakra", cleanedName: "13th Chakra (Earth Star)" },
    { name: "14th_Chakra", cleanedName: "14th Chakra (Solar Star)" },
    { name: "15th_Chakra", cleanedName: "15th Chakra (Galactic Core)" },
    { name: "Soul_Body", cleanedName: "Soul Body (6D)" },
    { name: "Monad", cleanedName: "Monad (Oversoul)" },
    { name: "Lightbody", cleanedName: "Lightbody Activation" },
    { name: "Merkaba", cleanedName: "Merkaba Field" },
    { name: "Kundalini", cleanedName: "Kundalini Energy" },
    { name: "Antahkarana", cleanedName: "Antahkarana Bridge" },
    { name: "Axiatonal_Lines", cleanedName: "Axiatonal Lines" },
    { name: "Nadial_Structure", cleanedName: "Nadial Structure" },
    { name: "12_Tree_Grid", cleanedName: "12 Tree Grid (Kathara)" },
    { name: "Astral_Plane", cleanedName: "Astral Plane (4D)" },
    { name: "Akashic_Records", cleanedName: "Akashic Records" },
    { name: "Violet_Flame", cleanedName: "The Violet Flame" },
    { name: "I_AM_Presence", cleanedName: "I AM Presence" },
    { name: "Threefold_Flame", cleanedName: "Threefold Flame" },
    { name: "12D_Shield", cleanedName: "12D Shield" },
    { name: "HGS_System", cleanedName: "HGS System" },
    { name: "Guardian_Alliance", cleanedName: "Guardian Alliance" },
    { name: "Negative_Alien_Agenda", cleanedName: "Negative Alien Agenda (NAA)" },
    { name: "Law_of_One", cleanedName: "The Law of One" },
];

export const CHAKRA_COLOR_MAP: { [key: string]: string } = {
    'root': '#FF0000',
    '1st chakra': '#FF0000',
    'muladhara': '#FF0000',
    'sacral': '#FFA500',
    '2nd chakra': '#FFA500',
    'svadhisthana': '#FFA500',
    'solar plexus': '#FFFF00',
    '3rd chakra': '#FFFF00',
    'manipura': '#FFFF00',
    'heart': '#008000',
    '4th chakra': '#008000',
    'anahata': '#008000',
    'throat': '#0000FF',
    '5th chakra': '#0000FF',
    'vishuddha': '#0000FF',
    'third eye': '#4B0082',
    '6th chakra': '#4B0082',
    'ajna': '#4B0082',
    'crown': '#8A2BE2',
    '7th chakra': '#8A2BE2',
    'sahasrara': '#8A2BE2',
    'soul star': '#FFFFFF',
    '8th chakra': '#FFFFFF',
    'spirit chakra': '#00FFFF',
    '9th chakra': '#00FFFF',
    'universal chakra': '#FFD700',
    '10th chakra': '#FFD700',
    'galactic chakra': '#FF1493',
    '11th chakra': '#FF1493',
    'stellar gateway': '#C0C0C0',
    '12th chakra': '#C0C0C0',
    'earth star': '#A52A2A', // Brown
    '13th chakra': '#A52A2A',
    'solar star': '#FFDF00',
    '14th chakra': '#FFDF00',
    'galactic core': '#ADD8E6',
    '15th chakra': '#ADD8E6',
    '12d shield': '#E5E7EB', // Light Gray
    'shield': '#E5E7EB',
    'hgs': '#FBBF24', // Amber
    'guardian': '#38BDF8', // Light Blue
};